export const SET_USER = 'SET_USER'
export const USER_ERROR = 'USER_ERROR'


export const LOGIN_USER = 'LOGIN_USER'
export const GET_ALL_TRANSACTION = 'GET_ALL_TRANSACTION'
export const CREATE_TRANSACTION = 'CREATE_TRANSACTION'
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION'